# dd-new-dev-db — postgres 18.3 · db.t4g.micro
# Generated by DeepAgent. Rerunning the wizard regenerates this file.
# Look up the EKS cluster's VPC + worker security groups.
# Requires the cluster to already exist (built by the eks/aks flow).
data "aws_eks_cluster" "target" {
  name = "dd-new-dev"
}

locals {
  eks_vpc_id        = data.aws_eks_cluster.target.vpc_config[0].vpc_id
  eks_cluster_sg_id = data.aws_eks_cluster.target.vpc_config[0].cluster_security_group_id
  # Workers use the "additional" SG when the cluster was built with one; fall
  # back to the cluster SG. Both are acceptable inbound sources for RDS.
  eks_worker_sg_ids = concat(
    tolist(data.aws_eks_cluster.target.vpc_config[0].security_group_ids),
    [data.aws_eks_cluster.target.vpc_config[0].cluster_security_group_id],
  )
}

data "aws_subnets" "tagged_private" {
  filter {
    name   = "vpc-id"
    values = [local.eks_vpc_id]
  }
  tags = { "kubernetes.io/role/internal-elb" = "1" }
}

data "aws_subnets" "all_in_vpc" {
  filter {
    name   = "vpc-id"
    values = [local.eks_vpc_id]
  }
}

locals {
  db_subnet_ids = length(data.aws_subnets.tagged_private.ids) >= 2 ? data.aws_subnets.tagged_private.ids : data.aws_subnets.all_in_vpc.ids
}

variable "db_master_password_override" {
  type        = string
  sensitive   = true
  description = "User-supplied RDS master password (wizard \"Set my own\" flow). Value is fed by terraform.tfvars.json alongside this file."
}

resource "aws_security_group" "rds" {
  name        = "dd-new-dev-db-rds-sg"
  # AWS SG description charset is strict — ASCII-only, no em-dash / arrow / etc.
  # (regex ^[0-9A-Za-z_ .:/()#,@\[\]+=&;{}!$*-]*$). Keep this line ASCII.
  description = "RDS postgres for dd-new-dev-db - inbound from EKS workers only"
  vpc_id      = local.eks_vpc_id
  tags        = {
    "ManagedBy" = "DeepAgent"
    "Database" = "dd-new-dev-db"
    "Engine" = "postgres"
    "Environment" = "dev"
  }
}

# Allow inbound Postgres/MySQL from EACH worker/cluster SG the EKS cluster uses.
# No 0.0.0.0/0 — the DB is only reachable from within the cluster's pods.
resource "aws_security_group_rule" "rds_ingress_from_eks" {
  count                    = length(local.eks_worker_sg_ids)
  type                     = "ingress"
  from_port                = 5432
  to_port                  = 5432
  protocol                 = "tcp"
  security_group_id        = aws_security_group.rds.id
  source_security_group_id = local.eks_worker_sg_ids[count.index]
  # AWS SG description charset is strict: ASCII only, and even the less-than
  # and greater-than characters are rejected (see aws_security_group.rds
  # above). No arrow-shaped strings like "->". Keep this line ASCII.
  description              = "EKS worker SG to RDS postgres on 5432"
}

resource "aws_security_group_rule" "rds_egress_all" {
  type              = "egress"
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  security_group_id = aws_security_group.rds.id
  cidr_blocks       = ["0.0.0.0/0"]
  description       = "RDS egress (DNS, package updates for maintenance)"
}

resource "aws_db_subnet_group" "rds" {
  name        = "dd-new-dev-db-subnets"
  description = "Subnets for the dd-new-dev-db postgres instance"
  subnet_ids  = local.db_subnet_ids
  tags        = {
    "ManagedBy" = "DeepAgent"
    "Database" = "dd-new-dev-db"
    "Engine" = "postgres"
    "Environment" = "dev"
  }

  # A database in a different VPC from its cluster is unreachable no matter
  # what the security groups say — and the failure surfaces much later as a
  # connection timeout the app gets blamed for. Fail at PLAN time instead,
  # before anything is created. Discovered subnets come from the cluster's own
  # VPC so this can only trip on explicitly-chosen ones.
  lifecycle {
    precondition {
      condition     = length(setsubtract(values(data.aws_subnet.db_selected)[*].vpc_id, [local.eks_vpc_id])) == 0
      error_message = "DB subnet group VPC != cluster VPC (${local.eks_vpc_id}). The chosen subnets live in ${join(", ", distinct(values(data.aws_subnet.db_selected)[*].vpc_id))}. Pick subnets inside the cluster's VPC."
    }
  }
}

# Resolves each chosen subnet so the precondition above can compare VPCs.
data "aws_subnet" "db_selected" {
  for_each = toset(local.db_subnet_ids)
  id       = each.value
}

# Custom parameter group so we can flip off the "force SSL" default.
# See parameterGroupParams() in src/lib/devops/rds.ts for the rationale —
# short version: AWS's default rejects unencrypted connections, apps that
# don't yet speak SSL crashloop with a misleading pg_hba.conf message,
# and DeepAgent's DATABASE_URL still carries sslmode=require so an app
# that DOES speak SSL is unchanged.
resource "aws_db_parameter_group" "rds" {
  name        = "dd-new-dev-db-params"
  family      = "postgres18"
  description = "DeepAgent-managed parameter group for dd-new-dev-db (SSL not forced; client-side SSL still works)"
  tags        = {
    "ManagedBy" = "DeepAgent"
    "Database" = "dd-new-dev-db"
    "Engine" = "postgres"
    "Environment" = "dev"
  }
  parameter {
    name         = "rds.force_ssl"
    value        = "0"
    apply_method = "immediate"
  }

  # A parameter group can't be dropped while an instance still references it,
  # and RDS holds the reference briefly during the swap. create_before_destroy
  # lets Terraform build the new one first, swap the instance over, then
  # remove the old — the opposite order deadlocks the apply.
  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_db_instance" "rds" {
  identifier             = "dd-new-dev-db"
  engine                 = "postgres"
  engine_version         = "18.3"
  parameter_group_name   = aws_db_parameter_group.rds.name

  instance_class         = "db.t4g.micro"
  allocated_storage      = 20
  max_allocated_storage  = 200
  storage_type           = "gp3"
  # Encryption cannot be toggled after creation — only restored-from-snapshot
  # into a new instance. Defaults on for that reason.
  storage_encrypted      = true

  # SQL Server rejects db_name outright (no initial database is created — the
  # app or a migration must issue CREATE DATABASE). For Oracle it is the SID.
  db_name                = "app"
  username               = "app"
  # This password lives in Terraform state AND in Secrets Manager (below).
  # Keep the state backend (S3) encrypted and least-privilege. For long-term
  # production migrate to IAM auth + IRSA (no static password).
  #
  # NOT using manage_master_user_password: that hands the password to AWS and
  # removes it from Terraform's outputs, which is where the pipeline reads it
  # to write the app's Kubernetes Secret. The explicit secret below gives the
  # same durability without breaking that hand-off.
  password               = var.db_master_password_override

  port                   = 5432
  db_subnet_group_name   = aws_db_subnet_group.rds.name
  vpc_security_group_ids = [aws_security_group.rds.id]
  publicly_accessible    = false

  backup_retention_period = 7
  backup_window           = "03:00-04:00"
  maintenance_window      = "sun:04:30-sun:05:30"
  auto_minor_version_upgrade = true
  copy_tags_to_snapshot   = true

  iam_database_authentication_enabled = false

  # Engine logs to CloudWatch, so the agent can read them through the existing
  # observability stack. Declared ONCE — Terraform rejects a repeated argument.
  enabled_cloudwatch_logs_exports = ["postgresql","upgrade"]

  multi_az               = false
  deletion_protection    = true
  skip_final_snapshot    = false
  final_snapshot_identifier = "dd-new-dev-db-final-${formatdate("YYYYMMDDhhmmss", timestamp())}"

  # Apply modifications immediately instead of deferring them to the next
  # maintenance window (default sun 04:30 UTC). A user clicking "Apply" on a
  # size / class change expects it to happen now, not up to a week later.
  # Instance-class change is still IN-PLACE (not destroy+recreate): AWS resizes
  # the underlying instance, with a brief failover for Multi-AZ and a short
  # outage for single-AZ.
  apply_immediately      = true

  tags = {
    "ManagedBy" = "DeepAgent"
    "Database" = "dd-new-dev-db"
    "Engine" = "postgres"
    "Environment" = "dev"
  }
}
